Repository ehdrhelr/airbnb, pull requests merged in 2021-06, with the labels that each got.

#41 [Fe] 카카오 Map
  FE/airbnb/.env.development
  FE/airbnb/.env.production
  FE/airbnb/package-lock.json
  FE/airbnb/package.json
  FE/airbnb/public/index.html
  FE/airbnb/src/App.tsx
  FE/airbnb/src/assets/image/hero-img.png
  FE/airbnb/src/assets/svg/Property 1=star.svg
  FE/airbnb/src/components/header/Background.tsx
  FE/airbnb/src/components/header/form/FormColumn.tsx
  FE/airbnb/src/components/header/form/FormLocation.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/calendar/FormCalendar.tsx
  FE/airbnb/src/components/header/form/calendar/calendarDateFn.tsx
  FE/airbnb/src/components/header/form/guestToggle/FormGuestToggle.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceBar.tsx
  FE/airbnb/src/components/map/Map.tsx
  FE/airbnb/src/components/map/MapLabel.tsx
  FE/airbnb/src/components/reserveHeader/ReserveForm.tsx
  FE/airbnb/src/components/reserveHeader/ReserveHeader.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoom.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomGrade.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomList.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomPrice.tsx
  FE/airbnb/src/components/reserveRoomList/RoomDescription.tsx
  FE/airbnb/src/components/reserveRoomList/roomType.ts
  FE/airbnb/src/pages/MainPage.tsx
  FE/airbnb/src/pages/ReservePage.tsx
  FE/airbnb/src/recoil/headerAtom.ts
  FE/airbnb/src/recoil/reserveRoomAtom.ts
  FE/airbnb/src/recoil/roomSampleData.ts
  FE/airbnb/src/util/api.ts
Labels: FE, enhancement

#45 [FE] 라우터 및 fetch 작업
  FE/airbnb/src/App.tsx
  FE/airbnb/src/components/header/form/FormCheckIn.tsx
  FE/airbnb/src/components/header/form/FormCheckOut.tsx
  FE/airbnb/src/components/header/form/FormGuest.tsx
  FE/airbnb/src/components/header/form/FormLocation.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/calendar/calendarDateFn.tsx
  FE/airbnb/src/components/map/Map.tsx
  FE/airbnb/src/components/reserveHeader/ReserveHeader.tsx
  FE/airbnb/src/components/reserveHeader/ReserveHeaderForm.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoom.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomPrice.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveForm.tsx
  FE/airbnb/src/components/util/ConditionalLink.tsx
  FE/airbnb/src/index.css
  FE/airbnb/src/pages/ReservePage.tsx
  FE/airbnb/src/recoil/headerAtom.ts
  FE/airbnb/src/recoil/reserveRoomAtom.ts
  FE/airbnb/src/util/api.ts
  FE/airbnb/src/util/util.js
Labels: FE, enhancement

#46 Guest Number Selection Scene 구현 / View와 View Model 분리
  iOS/AirBed&Breakfast/AirBed&Breakfast.xcodeproj/project.pbxproj
  iOS/AirBed&Breakfast/AirBed&Breakfast/Application/DIContainer/ReservationDetailViewControllerDIContainer.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Application/NotificationNameExtension.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Domain/GuestType.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/AccommodationSelectViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/ReservationDetailViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SearchViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SetUpViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/ViewModel/ReservationDetailViewModel.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/Base.lproj/Main.storyboard
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/CalendarView/CalendarControlView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/CalendarView/CalendarControlViewModel.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/NumberOfHeadSelectionView/GuestNumberSelectionView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/NumberOfHeadSelectionView/NumberAdjustmentView/NumberAdjustmentView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/PriceSlideView/PriceSlideControlView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/PriceSlideView/PriceSlideControlViewModel.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/PriceSlideView/RangeSlider.swift
Labels: iOS

#48 [FE]예약 폼 모달
  FE/airbnb/public/index.html
  FE/airbnb/src/App.tsx
  FE/airbnb/src/components/header/form/FormGuest.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceBar.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceChart.tsx
  FE/airbnb/src/components/reservePageSkeleton/MapSkeleton.tsx
  FE/airbnb/src/components/reservePageSkeleton/ReserveSkeleton.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoom.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomList.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveBtn.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveForm.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveFormHeader.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveFormInfo.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveFromPrice.tsx
  FE/airbnb/src/components/util/ConditionalLink.tsx
  FE/airbnb/src/pages/ReservePage.tsx
  FE/airbnb/src/recoil/headerAtom.ts
  FE/airbnb/src/recoil/reserveRoomAtom.ts
  FE/airbnb/src/util/api.ts
  FE/airbnb/src/util/util.js
Labels: FE, enhancement

#51 [FE] 리뷰 기반 리팩토링
  FE/airbnb/src/components/calendar/CalendarDate.tsx
  FE/airbnb/src/components/calendar/CalendarHeader.tsx
  FE/airbnb/src/components/commonComponents/ConditionalLink.tsx
  FE/airbnb/src/components/header/Header.tsx
  FE/airbnb/src/components/header/HoverBlock.tsx
  FE/airbnb/src/components/header/form/FormCheckIn.tsx
  FE/airbnb/src/components/header/form/FormCheckOut.tsx
  FE/airbnb/src/components/header/form/FormColumn.tsx
  FE/airbnb/src/components/header/form/FormGuest.tsx
  FE/airbnb/src/components/header/form/FormLocation.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/calendar/FormCalendar.tsx
  FE/airbnb/src/components/header/form/guestToggle/GuestColumn.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceBar.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceChart.tsx
  FE/airbnb/src/components/header/tab/HeaderTab.tsx
  FE/airbnb/src/components/map/Map.tsx
  FE/airbnb/src/components/reserveHeader/ReserveHeaderForm.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomList.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomPrice.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveForm.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveFormInfo.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveFromPrice.tsx
  FE/airbnb/src/pages/ReservePage.tsx
  FE/airbnb/src/recoilStore/calendarAtom.ts
  FE/airbnb/src/recoilStore/headerAtom.ts
  FE/airbnb/src/recoilStore/reserveRoomAtom.ts
  FE/airbnb/src/recoilStore/roomSampleData.ts
  FE/airbnb/src/util/api.ts
  FE/airbnb/src/util/calendarUtils.tsx
  FE/airbnb/src/util/tsUtils.ts
  FE/airbnb/src/util/util.js
  FE/airbnb/src/util/utilStyles.ts
Labels: FE

#52 Be/feature/api
  BE/airbnb/build.gradle
  BE/airbnb/src/main/java/team01/airbnb/config/SwaggerConfig.java
  BE/airbnb/src/main/java/team01/airbnb/config/WebConfig.java
  BE/airbnb/src/main/java/team01/airbnb/controller/AccommodationController.java
  BE/airbnb/src/main/java/team01/airbnb/controller/HomeController.java
  BE/airbnb/src/main/java/team01/airbnb/controller/ReservationController.java
  BE/airbnb/src/main/java/team01/airbnb/controller/UserController.java
  BE/airbnb/src/main/java/team01/airbnb/dto/Charge.java
  BE/airbnb/src/main/java/team01/airbnb/dto/request/AccommodationSaveRequestDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/request/TotalAccommodationSaveRequestDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/response/AccommodationAddressResponseDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/response/AccommodationResponseDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/response/AccommodationResultListResponseDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/response/ChargesResponseDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/response/ReservationViewResponseDto.java
  BE/airbnb/src/main/java/team01/airbnb/exception/AccommodationNotFoundException.java
  BE/airbnb/src/main/java/team01/airbnb/exceptionHandler/GlobalExceptionHandler.java
  BE/airbnb/src/main/java/team01/airbnb/repository/AccommodationRepository.java
  BE/airbnb/src/main/java/team01/airbnb/repository/ReservationRepository.java
  BE/airbnb/src/main/java/team01/airbnb/service/AccommodationService.java
  BE/airbnb/src/main/java/team01/airbnb/service/ReservationService.java
  BE/airbnb/src/main/resources/data.sql
  BE/airbnb/src/main/resources/templates/index.html
Labels: BE

#53 [FE]라우터 link reload 오류 해결
  FE/airbnb/src/components/header/form/FormGuest.tsx
  FE/airbnb/src/hooks/useToggle.ts
Labels: FE, bug

#55 [FE] 예약 요청
  FE/airbnb/src/components/reserveRoomList/ReserveRoom.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveBtn.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveForm.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveFromPrice.tsx
  FE/airbnb/src/pages/ReservePage.tsx
  FE/airbnb/src/recoilStore/reserveRoomAtom.ts
  FE/airbnb/src/util/api.ts
Labels: FE

#57 [FE] Map Label 오류 수정 및 지도 스켈레톤 UI
  FE/airbnb/package-lock.json
  FE/airbnb/package.json
  FE/airbnb/src/components/header/form/priceBar/PriceBar.tsx
  FE/airbnb/src/components/map/Map.tsx
  FE/airbnb/src/components/map/MapLabel.tsx
  FE/airbnb/src/components/reservePageSkeleton/MapSkeleton.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveBtn.tsx
Labels: bug, documentation, enhancement

#59 [FE] 예약 리스트 스켈레톤 UI
  FE/airbnb/src/components/reservePageSkeleton/MapSkeleton.tsx
  FE/airbnb/src/components/reservePageSkeleton/ReserveListSkeleton.tsx
  FE/airbnb/src/components/reservePageSkeleton/ReserveSkeleton.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoom.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomList.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomsSection.tsx
  FE/airbnb/src/pages/ReservePage.tsx
  FE/airbnb/src/recoilStore/headerAtom.ts
  FE/airbnb/src/util/calendarUtils.tsx
Labels: FE, enhancement

#60 [FE] 예약 스켈레톤 및 자잘한 오류 수정
  FE/airbnb/src/components/header/form/FormCheckIn.tsx
  FE/airbnb/src/components/header/form/FormCheckOut.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceBar.tsx
  FE/airbnb/src/components/map/Map.tsx
  FE/airbnb/src/components/reserveHeader/ReserveHeader.tsx
  FE/airbnb/src/components/reservePageSkeleton/ReserveSkeleton.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveEmptyRooms.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomList.tsx
Labels: bug, documentation, enhancement

#61 [FE]차트 예외 처리
  FE/airbnb/src/components/header/form/priceBar/PriceBar.tsx
  FE/airbnb/src/recoilStore/headerAtom.ts
Labels: FE, bug
