Repository ehdrhelr/airbnb, pull requests merged in 2021-05, with the labels that each got.

#8 iOS/feat/main scene UI
  iOS/AirBed&Breakfast/AirBed&Breakfast.xcodeproj/project.pbxproj
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controller/WelcomeViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/Base.lproj/Main.storyboard
Labels: iOS

#11 [FE]초기 셋팅
  FE/airbnb/.gitignore
  FE/airbnb/README.md
  FE/airbnb/package.json
  FE/airbnb/public/index.html
  FE/airbnb/public/manifest.json
  FE/airbnb/public/robots.txt
  FE/airbnb/src/App.css
  FE/airbnb/src/App.tsx
  FE/airbnb/src/components/main.tsx
  FE/airbnb/src/index.css
  FE/airbnb/src/index.tsx
  FE/airbnb/src/react-app-env.d.ts
  FE/airbnb/tsconfig.json
  FE/airbnb/yarn.lock
Labels: FE

#13 iOS/feat/search scene UI
  iOS/AirBed&Breakfast/AirBed&Breakfast.xcodeproj/project.pbxproj
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controller/SearchViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/Base.lproj/Main.storyboard
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/SearchResultCollectionView/SearchResultCollectionViewCell.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/SearchResultCollectionView/SearchResultCollectionViewCell.xib
Labels: iOS

#14 [#3] 카카오 로그인 구현
  BE/airbnb/.gitignore
  BE/airbnb/build.gradle
  BE/airbnb/shellscript/deploy-local.sh
  BE/airbnb/shellscript/deploy-webserver.sh
  BE/airbnb/src/main/java/team01/airbnb/config/WebConfig.java
  BE/airbnb/src/main/java/team01/airbnb/config/auth/LoginUser.java
  BE/airbnb/src/main/java/team01/airbnb/config/auth/LoginUserArgumentResolver.java
  BE/airbnb/src/main/java/team01/airbnb/config/auth/dto/SessionUser.java
  BE/airbnb/src/main/java/team01/airbnb/controller/HomeController.java
  BE/airbnb/src/main/java/team01/airbnb/controller/UserController.java
  BE/airbnb/src/main/java/team01/airbnb/domain/User.java
  BE/airbnb/src/main/java/team01/airbnb/dto/KakaoLogout.java
  BE/airbnb/src/main/java/team01/airbnb/dto/KakaoProfile.java
  BE/airbnb/src/main/java/team01/airbnb/dto/OAuthToken.java
  BE/airbnb/src/main/java/team01/airbnb/dto/RoleType.java
  BE/airbnb/src/main/java/team01/airbnb/service/UserService.java
  BE/airbnb/src/main/java/team01/airbnb/utils/KakaoLoginUtils.java
  BE/airbnb/src/main/resources/application.properties
  BE/airbnb/src/main/resources/data.sql
  BE/airbnb/src/main/resources/schema.sql
  BE/airbnb/src/main/resources/static/image/kakao_login_button.png
  BE/airbnb/src/main/resources/static/index.html
  BE/airbnb/src/main/resources/templates/index.html
  BE/airbnb/src/main/resources/templates/layout/footer.html
  BE/airbnb/src/main/resources/templates/layout/header.html
Labels: BE

#15 [#3] fix : 프사 있는 사용자가 로그인 해도 500에러 뜨지 않도록 수정
  BE/airbnb/src/main/java/team01/airbnb/dto/KakaoProfile.java
  BE/airbnb/src/main/java/team01/airbnb/service/UserService.java
Labels: BE, bug

#16 검색화면 UI요소 수정
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controller/SearchViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/SearchResultCollectionView/SearchResultCollectionViewCell.swift
Labels: iOS

#17 코드리뷰를 토대로 코드를 개선했습니다.
  BE/airbnb/.gitignore
  BE/airbnb/build.gradle
  BE/airbnb/src/main/java/team01/airbnb/config/WebConfig.java
  BE/airbnb/src/main/java/team01/airbnb/config/auth/LoginUserArgumentResolver.java
  BE/airbnb/src/main/java/team01/airbnb/config/interceptor/LoginInterceptor.java
  BE/airbnb/src/main/java/team01/airbnb/config/interceptor/LogoutInterceptor.java
  BE/airbnb/src/main/java/team01/airbnb/controller/UserController.java
  BE/airbnb/src/main/java/team01/airbnb/domain/User.java
  BE/airbnb/src/main/java/team01/airbnb/dto/ApiResult.java
  BE/airbnb/src/main/java/team01/airbnb/dto/KakaoLogout.java
  BE/airbnb/src/main/java/team01/airbnb/dto/KakaoProfile.java
  BE/airbnb/src/main/java/team01/airbnb/dto/SocialProfile.java
  BE/airbnb/src/main/java/team01/airbnb/exception/NoResultSetException.java
  BE/airbnb/src/main/java/team01/airbnb/exception/NotProcessJsonException.java
  BE/airbnb/src/main/java/team01/airbnb/exceptionHandler/GlobalExceptionHandler.java
  BE/airbnb/src/main/java/team01/airbnb/service/UserService.java
  BE/airbnb/src/main/java/team01/airbnb/utils/KakaoLoginUtils.java
  BE/airbnb/src/main/resources/schema.sql
  BE/airbnb/src/test/java/team01/airbnb/AirbnbApplicationTests.java
  BE/airbnb/src/test/java/team01/airbnb/service/UserServiceTest.java
Labels: BE, enhancement

#18 [FE]헤더 구현 및 예약 폼
  FE/airbnb/package-lock.json
  FE/airbnb/package.json
  FE/airbnb/src/App.tsx
  FE/airbnb/src/components/header/Header.tsx
  FE/airbnb/src/components/header/HoverBlock.tsx
  FE/airbnb/src/components/header/form/FormCalendar.tsx
  FE/airbnb/src/components/header/form/FormCheckIn.tsx
  FE/airbnb/src/components/header/form/FormCheckOut.tsx
  FE/airbnb/src/components/header/form/FormColumn.tsx
  FE/airbnb/src/components/header/form/FormGuest.tsx
  FE/airbnb/src/components/header/form/FormGuestToggle.tsx
  FE/airbnb/src/components/header/form/FormLocation.tsx
  FE/airbnb/src/components/header/form/FormLocationToggle.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/FormPriceToggle.tsx
  FE/airbnb/src/components/header/form/HeaderForm.tsx
  FE/airbnb/src/components/header/nav/HeaderNav.tsx
  FE/airbnb/src/components/header/nav/NavUserToggle.tsx
  FE/airbnb/src/components/header/tab/HeaderTab.tsx
  FE/airbnb/src/components/header/tab/HeaderTabList.tsx
  FE/airbnb/src/components/main.tsx
  FE/airbnb/src/components/svg/svg.js
  FE/airbnb/src/components/util/utilStyles.ts
  FE/airbnb/src/hooks/useToggle.ts
  FE/airbnb/src/index.css
  FE/airbnb/src/index.tsx
  FE/airbnb/src/pages/MainPage.tsx
  FE/airbnb/src/recoil/headerAtom.ts
  FE/airbnb/src/theme.ts
Labels: FE

#20 [#4] chore : DB 설계 후 entity 및 더미데이터 추가
  BE/airbnb/src/main/java/team01/airbnb/domain/Amenity.java
  BE/airbnb/src/main/java/team01/airbnb/domain/Reservation.java
  BE/airbnb/src/main/java/team01/airbnb/domain/User.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/Accommodation.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/AccommodationAddress.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/AccommodationCondition.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/AccommodationPhoto.java
  BE/airbnb/src/main/java/team01/airbnb/service/UserService.java
  BE/airbnb/src/main/resources/data.sql
  BE/airbnb/src/main/resources/schema.sql
Labels: BE

#21 날짜 입력 화면 구현
  iOS/AirBed&Breakfast/AirBed&Breakfast.xcodeproj/project.pbxproj
  iOS/AirBed&Breakfast/AirBed&Breakfast.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/AirBed&Breakfast/AirBed&Breakfast/Application/DateExtension.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/DateSelectionViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/ReservationDetailViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SearchViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/WelcomeViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/Base.lproj/Main.storyboard
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/CalendarView/DayLabel.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/CalendarView/DayRangeIndicatorView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/ReservationDetailTableView/ReservationDetailTableViewCell.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/ReservationDetailTableView/ReservationDetailTableViewCell.xib
Labels: iOS

#22 [FE] 캘린더 UI 구현
  FE/airbnb/package-lock.json
  FE/airbnb/package.json
  FE/airbnb/src/assets/svg/Property 1=check.svg
  FE/airbnb/src/assets/svg/Property 1=chevron-left.svg
  FE/airbnb/src/assets/svg/Property 1=chevron-right.svg
  FE/airbnb/src/assets/svg/Property 1=heart.svg
  FE/airbnb/src/assets/svg/Property 1=menu.svg
  FE/airbnb/src/assets/svg/Property 1=minus-circle.svg
  FE/airbnb/src/assets/svg/Property 1=pause-circle.svg
  FE/airbnb/src/assets/svg/Property 1=plus-circle.svg
  FE/airbnb/src/assets/svg/Property 1=search.svg
  FE/airbnb/src/assets/svg/Property 1=star.svg
  FE/airbnb/src/assets/svg/Property 1=user.svg
  FE/airbnb/src/assets/svg/Property 1=x-circle.svg
  FE/airbnb/src/assets/svg/minus.svg
  FE/airbnb/src/assets/svg/plus.svg
  FE/airbnb/src/components/calendar/Calendar.tsx
  FE/airbnb/src/components/calendar/CalendarDate.tsx
  FE/airbnb/src/components/calendar/CalendarHeader.tsx
  FE/airbnb/src/components/header/form/FormCalendar.tsx
  FE/airbnb/src/components/header/form/FormCheckIn.tsx
  FE/airbnb/src/components/header/form/FormCheckOut.tsx
  FE/airbnb/src/components/header/form/FormGuest.tsx
  FE/airbnb/src/components/header/form/FormLocationToggle.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/HeaderForm.tsx
  FE/airbnb/src/components/header/nav/HeaderNav.tsx
  FE/airbnb/src/components/header/nav/NavUserToggle.tsx
  FE/airbnb/src/components/svg/svg.js
  FE/airbnb/src/hooks/useToggle.ts
  FE/airbnb/src/recoil/headerAtom.ts
Labels: FE

#23 [#19][FE] calendar css 수정
  FE/airbnb/src/components/header/form/FormCheckIn.tsx
  FE/airbnb/src/components/header/form/FormCheckOut.tsx
  FE/airbnb/src/components/header/form/FormGuest.tsx
  FE/airbnb/src/components/header/form/FormLocation.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
Labels: FE

#25 [BE] 전체 숙소 목록 보기 & 숙소 등록 기능 추가
  BE/airbnb/src/main/java/team01/airbnb/config/WebConfig.java
  BE/airbnb/src/main/java/team01/airbnb/controller/AccommodationController.java
  BE/airbnb/src/main/java/team01/airbnb/controller/UserController.java
  BE/airbnb/src/main/java/team01/airbnb/domain/Amenity.java
  BE/airbnb/src/main/java/team01/airbnb/domain/Reservation.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/Accommodation.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/AccommodationAddress.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/AccommodationCondition.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/AccommodationPhoto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/OAuthToken.java
  BE/airbnb/src/main/java/team01/airbnb/dto/request/AccommodationSaveRequestDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/response/AccommodationResponseDto.java
  BE/airbnb/src/main/java/team01/airbnb/exception/ConditionNotFoundException.java
  BE/airbnb/src/main/java/team01/airbnb/exceptionHandler/GlobalExceptionHandler.java
  BE/airbnb/src/main/java/team01/airbnb/repository/AccommodationRepository.java
  BE/airbnb/src/main/java/team01/airbnb/service/AccommodationService.java
  BE/airbnb/src/main/java/team01/airbnb/service/UserService.java
  BE/airbnb/src/main/resources/data.sql
  BE/airbnb/src/main/resources/schema.sql
  BE/airbnb/src/main/resources/templates/form.html
  BE/airbnb/src/main/resources/templates/index.html
  BE/airbnb/src/test/java/team01/airbnb/repository/AccommodationRepositoryTest.java
Labels: BE

#26 Price selection 뷰 UI 구현
  iOS/AirBed&Breakfast/AirBed&Breakfast.xcodeproj/project.pbxproj
  iOS/AirBed&Breakfast/AirBed&Breakfast/Application/DateExtension.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/ReservationDetailViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SearchViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SetUpViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/WelcomeViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/Base.lproj/Main.storyboard
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/CalendarView/CalendarControlView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/PriceSlideView/PriceSlideControlView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/PriceSlideView/RangeSlider.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/ReservationDetailTableView/ReservationDetailTableViewCell.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/SearchResultCollectionView/SearchResultCollectionViewCell.swift
Labels: iOS

#29 [FE] 리뷰 기반 리팩토링
  FE/airbnb/src/components/header/form/calendar/FormCalendar.tsx
  FE/airbnb/src/components/header/tab/HeaderTabList.tsx
Labels: FE

#31 [FE][#30] 체크인 체크아웃 토글 수정
  FE/airbnb/src/components/header/HoverBlock.tsx
  FE/airbnb/src/components/header/form/FormCheckIn.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/FormPriceToggle.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceBar.tsx
  FE/airbnb/src/hooks/useToggle.ts
Labels: FE

#32 [BE] 코드리뷰에 따라 코드를 개선하라.
  BE/airbnb/src/main/java/team01/airbnb/controller/AccommodationController.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/Accommodation.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/AccommodationAddress.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/AccommodationCondition.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/AccommodationPhoto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/Charge.java
  BE/airbnb/src/main/java/team01/airbnb/dto/kakaoOauth/KakaoLogout.java
  BE/airbnb/src/main/java/team01/airbnb/dto/kakaoOauth/KakaoProfile.java
  BE/airbnb/src/main/java/team01/airbnb/dto/kakaoOauth/OAuthToken.java
  BE/airbnb/src/main/java/team01/airbnb/dto/request/AccommodationSaveRequestDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/request/ConditionSaveRequestDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/request/TotalAccommodationSaveRequestDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/response/AccommodationResponseDto.java
  BE/airbnb/src/main/java/team01/airbnb/exception/ConditionNotFoundException.java
  BE/airbnb/src/main/java/team01/airbnb/exception/NoResultSetException.java
  BE/airbnb/src/main/java/team01/airbnb/exceptionHandler/GlobalExceptionHandler.java
  BE/airbnb/src/main/java/team01/airbnb/repository/AccommodationRepository.java
  BE/airbnb/src/main/java/team01/airbnb/service/AccommodationService.java
  BE/airbnb/src/main/java/team01/airbnb/service/UserService.java
  BE/airbnb/src/main/resources/data.sql
  BE/airbnb/src/main/resources/schema.sql
  BE/airbnb/src/main/resources/templates/form.html
Labels: BE, enhancement

#33 [FE]차트 UI 구현
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceBar.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceChart.tsx
  FE/airbnb/src/components/header/form/priceBar/priceType.ts
  FE/airbnb/src/components/header/form/priceBar/sampleData.ts
  FE/airbnb/src/components/util/util.ts
Labels: FE

#36 [FE]리뷰 기반 리팩토링
  FE/airbnb/src/components/calendar/CalendarDate.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/calendar/FormCalendar.tsx
Labels: FE

#38 [Fe] guest UI 모달 구현
  FE/airbnb/src/assets/svg/Property 1=minus-circle.svg
  FE/airbnb/src/assets/svg/Property 1=plus-circle.svg
  FE/airbnb/src/components/calendar/CalendarDate.tsx
  FE/airbnb/src/components/header/form/FormGuest.tsx
  FE/airbnb/src/components/header/form/FormGuestToggle.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/guestToggle/FormGuestToggle.tsx
  FE/airbnb/src/components/header/form/guestToggle/GuestColumn.tsx
  FE/airbnb/src/components/header/form/guestToggle/guestType.ts
  FE/airbnb/src/components/header/form/priceBar/PriceBar.tsx
  FE/airbnb/src/recoil/headerAtom.ts
Labels: FE, enhancement

#39 [Fe] 메인 UI
  FE/airbnb/public/image/hero-img.png
  FE/airbnb/src/App.tsx
  FE/airbnb/src/assets/svg/Property 1=x-circle.svg
  FE/airbnb/src/components/calendar/CalendarDate.tsx
  FE/airbnb/src/components/header/Header.tsx
  FE/airbnb/src/components/header/HoverBlock.tsx
  FE/airbnb/src/components/header/form/FormCheckIn.tsx
  FE/airbnb/src/components/header/form/FormCheckOut.tsx
  FE/airbnb/src/components/header/form/FormColumn.tsx
  FE/airbnb/src/components/header/form/FormGuest.tsx
  FE/airbnb/src/components/header/form/FormLocation.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/HeaderForm.tsx
  FE/airbnb/src/components/header/form/guestToggle/GuestColumn.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceBar.tsx
  FE/airbnb/src/components/header/tab/HeaderTabList.tsx
  FE/airbnb/src/index.css
  FE/airbnb/src/pages/MainPage.tsx
  FE/airbnb/src/recoil/calendarAtom.ts
  FE/airbnb/src/recoil/headerAtom.ts
Labels: FE, enhancement
